/**
 * mock.ts
 * -------
 * A fake Layla native host for running the SDK OUTSIDE the app (Vite dev server,
 * Storybook, a browser test, etc.). It installs a stand-in
 * `window.ReactNativeWebView` and answers the web->RN commands by dispatching the
 * same `MessageEvent`s the real host would, so the SDK's bridge, queue,
 * streaming, and cancel paths all run for real against it.
 *
 * Usage (Vite — install in dev before you use the SDK):
 *
 *   // main.ts
 *   if (import.meta.env.DEV) {
 *     const { installLaylaMock } = await import('layla-sdk/mock');
 *     installLaylaMock({ debug: true });
 *   }
 *
 * Install BEFORE the SDK posts its first message; otherwise the bridge sees no
 * host and rejects with LaylaBridgeUnavailableError.
 */

import type {
  LaylaApiEvent,
  LaylaApiRequest,
  LaylaCharacter,
  LaylaChatMessage,
  TavernCardV2,
} from './protocol';

type MockReply =
  | string
  | string[]
  | Iterable<string>
  | AsyncIterable<string>;

export interface LaylaMockOptions {
  /**
   * Produce the assistant reply for a `send_message`. Return a string (which the
   * mock tokenises and streams), an array of pre-split tokens, or an
   * (async) iterable of tokens for full control over timing/content. May be
   * async. Defaults to a canned reply that echoes the last user message.
   */
  respond?: (messages: LaylaChatMessage[]) => MockReply | Promise<MockReply>;
  /** Cards returned by `get_characters`. Defaults to two sample cards. */
  characters?: LaylaCharacter[];
  /** Delay before the first event of a response (simulated latency). Default 150ms. */
  latencyMs?: number;
  /** Delay between streamed tokens. Default 40ms. */
  tokenDelayMs?: number;
  /** 0..1 probability that a request fails with on_error, for testing error paths. Default 0. */
  errorRate?: number;
  /** Log every web->RN command and RN->web event to the console. */
  debug?: boolean;
}

export interface LaylaMockHandle {
  /** Remove the fake bridge and restore whatever was there before. */
  uninstall(): void;
}

const delay = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

/** Build a valid Character Card V2 with sensible mock defaults. */
export function makeMockCharacter(
  name: string,
  overrides: Partial<TavernCardV2['data']> = {},
): LaylaCharacter {
  return {
    id: `mock-${name.toLowerCase()}`,
    data: {
      spec: 'chara_card_v2',
      spec_version: '2.0',
      data: {
        name,
        description: `${name} is a mock character for local testing.`,
        personality: 'friendly, helpful',
        scenario: '',
        first_mes: `Hi, I'm ${name}.`,
        mes_example: '',
        creator_notes: 'Generated by layla mock.',
        system_prompt: '',
        post_history_instructions: '',
        alternate_greetings: [],
        tags: ['mock'],
        creator: 'layla-mock',
        character_version: '1.0',
        extensions: {},
        ...overrides,
      },
    }
  };
}

export function installLaylaMock(options: LaylaMockOptions = {}): LaylaMockHandle {
  if (typeof window === 'undefined') {
    throw new Error(
      'installLaylaMock needs a browser-like environment (window). ' +
      'In Node, run your test under jsdom or happy-dom.',
    );
  }

  const latencyMs = options.latencyMs ?? 150;
  const tokenDelayMs = options.tokenDelayMs ?? 40;
  const errorRate = options.errorRate ?? 0;
  const characters =
    options.characters ?? [makeMockCharacter('Aria'), makeMockCharacter('Kai')];

  // The single in-flight generation, mirroring the SDK's one-active-job model.
  let current: { cancelled: boolean } | null = null;

  const log = (...a: unknown[]) => {
    if (options.debug) console.log('[layla-mock]', ...a);
  };

  /** RN -> web: dispatch an event exactly the way the WebView host does. */
  const emit = (event: LaylaApiEvent): void => {
    log('RN->web', event);
    window.dispatchEvent(new MessageEvent('message', { data: JSON.stringify(event) }));
  };

  const emitError = (message: string) =>
    emit({ event: 'on_error', data: { message } });

  const shouldError = () => errorRate > 0 && Math.random() < errorRate;

  const tokenize = (text: string): string[] =>
    text.match(/\S+\s*/g) ?? (text ? [text] : []);

  const defaultReply = (messages: LaylaChatMessage[]): string => {
    const lastUser = [...messages].reverse().find((m) => m.role === 'user');
    const said = lastUser?.content ?? '(nothing)';
    return (
      `This is a mock Layla response. You said: "${said}". ` +
      `Tokens stream one at a time so you can exercise your streaming UI, ` +
      `cancellation, and the final-content promise.`
    );
  };

  async function* tokenSource(
    messages: LaylaChatMessage[],
  ): AsyncGenerator<string> {
    const produced = options.respond
      ? await options.respond(messages)
      : defaultReply(messages);

    if (typeof produced === 'string') {
      yield* tokenize(produced);
      return;
    }
    if (Array.isArray(produced)) {
      yield* produced;
      return;
    }
    if (produced && typeof produced === 'object') {
      if (Symbol.asyncIterator in produced) {
        yield* produced as AsyncIterable<string>;
        return;
      }
      if (Symbol.iterator in produced) {
        yield* produced as Iterable<string>;
      }
    }
  }

  async function handleSend(messages: LaylaChatMessage[]): Promise<void> {
    const gen = { cancelled: false };
    current = gen;
    try {
      await delay(latencyMs);
      if (gen.cancelled) return; // cancel ack already emitted

      if (shouldError()) {
        emitError('Simulated model error');
        return;
      }

      let snapshot = '';
      for await (const delta of tokenSource(messages)) {
        if (gen.cancelled) return;
        snapshot += delta;
        emit({ event: 'on_message', data: { msg: snapshot, delta } });
        await delay(tokenDelayMs);
        if (gen.cancelled) return;
      }
      emit({ event: 'on_message_end' });
    } finally {
      if (current === gen) current = null;
    }
  }

  function handleCancel(): void {
    // Native contract: stop generating, then send the terminating on_message_end
    // that the SDK waits on before starting the next queued request. Emit it
    // asynchronously — a real RN bridge never delivers events synchronously
    // inside postMessage, and doing so here would re-enter the SDK's bridge.
    if (current && !current.cancelled) {
      current.cancelled = true;
      queueMicrotask(() => emit({ event: 'on_message_end' }));
    }
  }

  async function handleGetCharacters(data: { offset: number; limit: number }): Promise<void> {
    await delay(latencyMs);
    if (shouldError()) {
      emitError('Simulated characters error');
      return;
    }

    const { offset, limit } = data;
    emit({
      event: 'on_get_characters_response',
      data: characters.slice(offset, offset + limit),
    });
  }

  async function handleGetCharacterImage(data: { character_id: string }): Promise<void> {
    await delay(latencyMs);
    if (shouldError()) {
      emitError('Simulated character image error');
      return;
    }
    // This mock doesn't support images, but we have to return something valid.
    emit({
      event: 'on_get_character_image_response',
      data: {
        character_id: data.character_id,
        image_data_base64: 'https://picsum.photos/id/237/200/300',    // we return a url for mock, since we usually use this as the "src" of an <img> tag, it should work fine as a mock
      },
    });
  }

  async function handleGenerateImage(_: { prompt: string }): Promise<void> {
    await delay(latencyMs);
    if (shouldError()) {
      emitError('Simulated image generation error');
      return;
    }

    // Simulate progress events
    const totalSteps = 5;
    for (let step = 1; step <= totalSteps; step++) {
      await delay(latencyMs);
      emit({
        event: 'on_generate_image_progress',
        data: {
          status: `Generating image... (${step}/${totalSteps})`,
          steps: step,
          total_steps: totalSteps,
        },
      });
    }

    // Emit the final image response (using a placeholder image URL for the mock)
    emit({
      event: 'on_generate_image_response',
      data: {
        image_data_base64: 'https://picsum.photos/200/300', // Placeholder image URL for the mock
      },
    });
  }

  const fakeBridge = {
    postMessage(raw: string): void {
      let msg: LaylaApiRequest;
      try {
        msg = JSON.parse(raw);
      } catch {
        return; // not ours
      }
      log('web->RN', msg);
      switch (msg.cmd) {
        case 'send_message':
          void handleSend(msg.data);
          break;
        case 'cancel':
          handleCancel();
          break;
        case 'get_characters':
          void handleGetCharacters(msg.data);
          break;
        case 'get_character_image':
          void handleGetCharacterImage(msg.data);
          break;
        case 'generate_image':
          void handleGenerateImage(msg.data);
          break;
        default:
          break;
      }
    },
  };

  const previous = window.ReactNativeWebView;
  if (previous) {
    log('warning: replacing an existing window.ReactNativeWebView');
  }
  window.ReactNativeWebView = fakeBridge;
  log('installed');

  let installed = true;
  return {
    uninstall() {
      if (!installed) return;
      installed = false;
      if (current) current.cancelled = true;
      if (previous) window.ReactNativeWebView = previous;
      else delete window.ReactNativeWebView;
      log('uninstalled');
    },
  };
}

export default installLaylaMock;
